### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by MrThiemann** [Farmer-Eds-Shed/Node-Red-Google-API-Flows#3]
Thank you for this great flow!!!

unfortunately I get an error message after I have authorized myself.
Can you do something with that?

```
TypeError: Cannot read properties of undefined (reading 'split')
    at /root/.node-red/node_modules/node-red-contrib-google-calendar/source/google.js:211:37
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/usr/local/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:280:10)
    at query (/usr/local/lib/node_modules/node-red/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by Farmer-Eds-Shed** [comment]
Thanks @MrThiemann 
So it authenticates OK then you get the error when trying to make requests?
Are you trying to use one of my example request flows? The error above looks like it came from a  contrib node,  node-red-contrib-google-calendar. 

Are you trying to use node-red-contrib-google-calendar in conjunction with my flow some way?

I believe node-red-contrib-google-calendar has been broken for some time, doesn't look like there is much intention to fix it
https://flows.nodered.org/node/node-red-contrib-google-calendar
https://github.com/taminhhienmor/node-red-contrib-google-calendar

If you provide a little more detail on what you are trying to do, I'll see if I can help.

**Comment by Farmer-Eds-Shed** [comment]
No response
